[metadata]
name = achstripes
version = 0.1.0
description = Utilities for achstripes
author = Marcus Daghlian
author_email = marcusdag@googlemail.com

[options]
packages = find:
install_requires =
    matplotlib
    numpy
    seaborn
    scipy
    regex
    PyYAML
    pandas
    tqdm

[options.packages.find]
include =
    achstripes
    achstripes.*

[options.package_data]
achstripes =
    *.json